### ISSUE TITLE
[Feature Request] Support chained parameters in search

### ISSUE THREAD

**Issue by ghost** [awslabs/fhir-works-on-aws-search-es#104]
**Is your feature request related to a problem? Please describe.**
Here is an example of the query we are trying to execute.
{{API_URL}}/Encounter?status=in-progress&patient:Patient.name=John&_include:iterate=Encounter:patient
Basically we are trying to get all encounters that match the patients name in the Patient resource.

**Describe the solution you'd like**
Query to return the correct records

**Additional context**
 
1. The modifier to be explicit about the intended reference type (the “patient:Patient” part)
https://www.hl7.org/fhir/search.html#reference
2. The use of chained parameters (the “.name” part)
https://www.hl7.org/fhir/search.html#chaining

**Comment by rsmayda** [comment]
Thanks for the suggestion! To help with setting priority, is this a blocking feature request?

**Comment by ghost** [comment]
> Thanks for the suggestion! To help with setting priority, is this a blocking feature request?

Currently it is not a blocking feature request.

**Comment by ghost** [comment]
The US Core IG stipulates searching practitioner role by practitioner name and identifier using chained parameters using the practitioner search parameter SHALL be supported.

<img width="970" alt="image" src="https://user-images.githubusercontent.com/69013924/133838840-36a4497a-2d13-4374-89f7-c5f68abd98d3.png">

http://www.hl7.org/fhir/us/core/StructureDefinition-us-core-practitionerrole.html

**Comment by carvantes** [comment]
Hi,

We released the chained search parameters feature as part of fhir-works-on-aws-search-es@3.8.0

Please try it out and let us know if you have any feedback
