### ISSUE TITLE
[Feature Request] support both [type]/[id] and [id] when searching by reference

### ISSUE THREAD

**Issue by ghost** [awslabs/fhir-works-on-aws-search-es#106]
**Is your feature request related to a problem? Please describe.**
Inferno search by patient tests fail

![image](https://user-images.githubusercontent.com/69013924/130281735-02de1c6d-856e-4d41-965c-4e7d124184bd.png)

**Describe the solution you'd like**
Both forms of the search to return the same results

**Describe alternatives you've considered**

**Additional context**
US Core search guidance states servers shall support both forms of the reference search

http://hl7.org/fhir/us/core/general-guidance.html#search-syntax

**Comment by rsmayda** [comment]
Thanks for bringing this up we will add it to our backlog and prioritize it soon!

**Comment by rsmayda** [comment]
FYI in situations where there is multiple types allowed, this is what we will do:

> Some references may point to more than one type of resource; e.g. subject: Reference(Patient|Group|Device|..). In these cases, multiple resources may have the same logical identifier. Servers SHOULD reject a search where the logical id refers to more than one matching resource across different types. In order to allow the client to perform a search in these situations the type is specified explicitly

http://hl7.org/fhir/R4/search.html#reference

**Comment by carvantes** [comment]
> FYI in situations where there is multiple types allowed, this is what we will do:
> 
> > Some references may point to more than one type of resource; e.g. subject: Reference(Patient|Group|Device|..). In these cases, multiple resources may have the same logical identifier. Servers SHOULD reject a search where the logical id refers to more than one matching resource across different types. In order to allow the client to perform a search in these situations the type is specified explicitly
> 
> http://hl7.org/fhir/R4/search.html#reference

@rsmayda rejecting such requests is a SHOULD not a SHALL, so it's not hard requirement. I do think it's easier to simply reject them, but some FHIR servers accept them

Notably, HAPI actually accepts such requests. All the following queries are valid even though the `subject` parameter has an ambiguous target resource type (`Observation.subject(Group, Device, Patient, Location)`)

http://hapi.fhir.org/baseR4/Observation?subject=247816
http://hapi.fhir.org/baseR4/Observation?subject=Group/247816
http://hapi.fhir.org/baseR4/Observation?subject=Patient/126
http://hapi.fhir.org/baseR4/Observation?subject=126

**Comment by rsmayda** [comment]
@medhost-bfindeisen is the rejection behavior okay? 
i.e. http://hapi.fhir.org/baseR4/Observation?subject=247816 -> results in a 400 or empty result

**Comment by ghost** [comment]
Inferno expects both forms to succeed and return the same result.  

Using AllergyIntolerance and HAPI as an example these 2 calls return the same result:

http://hapi.fhir.org/baseR4/AllergyIntolerance?patient=2534062
http://hapi.fhir.org/baseR4/AllergyIntolerance?patient=Patient/2534062

and here are the resources returned:
 http://hapi.fhir.org/baseR4/AllergyIntolerance/2534138
 http://hapi.fhir.org/baseR4/AllergyIntolerance/2534139

both use the patient reference of:
![image](https://user-images.githubusercontent.com/69013924/130861458-3b768774-57e8-492e-bbbf-15e5bd40df02.png)

**Comment by rsmayda** [comment]
Yeah so we would support `baseR4/AllergyIntolerance?patient=2534062` since `AllergyIntolerance.patient` maps to just the 'Patient' resourceType. We would **NOT** support `baseR4/AllergyIntolerance?recorder=2534062` since `recorder` maps to **MANY** resourceType

 https://www.hl7.org/fhir/allergyintolerance.html

**Comment by ghost** [comment]
Apologies for not really answering your question.  I interpreted the rejection criteria slightly differently.  Since the logical id is defined as being

"unique within the space of all resources of the same type on the same server" 

it should be rejected in the case of more than 1 matching resource.  Given the design of FHIR Works this scenario would never happen.  Thoughts?

**Comment by rsmayda** [comment]
Merged in and released!
