### ISSUE TITLE
[Feature Request] Contains search support

### ISSUE THREAD

**Issue by rsmayda** [awslabs/fhir-works-on-aws-search-es#109]
We would like to see the contains string search added:

**[base]/Patient?given:contains=eve**	

Any patients with a name with a given part containing "eve" at any position. This would include patients with the given name "Eve", "Evelyn", and also "Severine".

Of course it would be nice to support all 3 string search scenarios mentioned in 3.1.1.4.8:

- **[base]/Patient?given=eve**	
  Any patients with a name containing a given part with "eve" at the start of the name. This would include patients with the given name "Eve", "Evelyn".

- **[base]/Patient?given:contains=eve**	
  Any patients with a name with a given part containing "eve" at any position. This would include patients with the given name "Eve", "Evelyn", and also "Severine".

- **[base]/Patient?given:exact=Eve**	
  Any patients with a name with a given part that is exactly "Eve". Note: This would not include patients with the given name "eve" or "EVE".

_Originally posted by @medhost-bfindeisen in https://github.com/awslabs/fhir-works-on-aws-search-es/issues/7#issuecomment-906689811_

**Comment by carvantes** [comment]
Support for `:contains` was added on https://github.com/awslabs/fhir-works-on-aws-search-es/pull/113
Support for `:exact` was added on https://github.com/awslabs/fhir-works-on-aws-search-es/pull/108
