### ISSUE TITLE
[Misc] Search sorting and score

### ISSUE THREAD

**Issue by gopalp19** [awslabs/fhir-works-on-aws-search-es#112]
**What's on your mind?**
1. For search requests, is it safe to assume the closest match is sorted at the beginning of the result array? Is there a sorting order for searches?
2. When will the search.score feature be available in search?

**Versions (please complete the following information):**
 - 3.4.0

**Comment by carvantes** [comment]
Hi, 

> 1. For search requests, is it safe to assume the closest match is sorted at the beginning of the result array? Is there a sorting order for searches?


In most cases, yes. We simply use the default sorting of Elasticsearch. Elasticsearch by default sorts search results by "relevance score" so the "closest matches" appear as the first results. 
Note that Elasticsearch uses the internal doc id as tie breaker for when sorting documents with the same relevance (e.g consider searching Patients by gender=female, many patients will have an exact gender match and have identical relevance score, thus the results will be ordered by the internal doc id which is not meaningful in the real world)

>2. When will the search.score feature be available in search?

Do you mean the `_score` parameter? There is very little documentation around `_score` on the FHIR website:
> To sort by relevance, use _score. 

Could you share a bit more about your use case for using `_score`? If possible, could you share the syntax of a search query that uses _score (e.g `GET /Patient?_score=<???>`)
