### ISSUE TITLE
Chained search parameters should resolve to exactly one resource type

### ISSUE THREAD

**Issue by ghost** [awslabs/fhir-works-on-aws-search-es#166]
**Describe the bug**
Some chained search parameter searches are erroring with '...points to multiple resource types, please specify'.  FHIR specifies that chained params must resolve to exactly one resourceType but the currently the code only looks at the target array when deciding if chained parameters are ambiguous

**To Reproduce**
Perform a DocumentReference search request: /DocumentReference?patient.identifier=2.16.840.1.113883.3.1579|8889154591540

**Expected behavior**
a search against the DocumentReference patient identifier

**Additional context**
The search param definition has "target" : ["Patient", "Group"] but its expression is “DocumentReference.subject.where(resolve() is Patient)”. Logically this means that the search parameter can only match Patient

**Comment by nguyen102** [comment]
Thanks for the bug report. We're currently working on a fix for this bug and will keep this issue updated with our progress.

**Comment by ssvegaraju** [comment]
Hi, we have just merged a fix for this issue into mainline, and it should be available with search-es v3.9.4!
