### ISSUE TITLE
include/revinclude parameters are not strictly validated

### ISSUE THREAD

**Issue by ghost** [awslabs/fhir-works-on-aws-search-es#167]
**Describe the bug**
Currently the include/revinclude parameters are not strictly validated, they are silently dropped during the query execution if they are invalid

**To Reproduce**
Perform a DocuumentReference search with invalid parameters: /DocumentReference?_include=DocumentReference:sourcePatientInfo

**Expected behavior**
Validation to be performed on the parameters instead of being silently dropped

**Comment by nguyen102** [comment]
@medhost-bfindeisen Do you have a link to documentation of what the proper response should be? Should we no results to be returned and an error message to be shown to the user? What would the error response look like?

**Comment by carvantes** [comment]
@nguyen102 , I think that when params are invalid, the error msg should be similar to the one in HAPI FHIR:

http://hapi.fhir.org/baseR4/DocumentReference?_include=DocumentReference:lalala
```
Invalid _include parameter value: "DocumentReference:lalala". Unknown search parameter "lalala" for resource type "DocumentReference".```

**Comment by nguyen102** [comment]
@carvantes thank you for the clarification. @medhost-bfindeisen I've added this bug to our backlog.

**Comment by kcadette** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com](mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake](https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
