### ISSUE TITLE
Return errors for invalid search parameter instead of returning empty list

### ISSUE THREAD

**Issue by arthuston** [awslabs/fhir-works-on-aws-search-es#17]
The AWS FHIR Server allows any search parameter name and returns an empty list. It should return an error.

For an example error, see http://hapi.fhir.org/baseR4/Observation?foo=bar

{{HTTP 400 Bad Request}}

"diagnostics": "Unknown search parameter \"foo\" for resource type \"[_id, _language, based-on, category, code, code-value-concept, code-value-date, code-value-quantity, code-value-string, combo-code, combo-code-value-concept, combo-code-value-quantity, combo-data-absent-reason, combo-value-concept, combo-value-quantity, component-code, component-code-value-concept, component-code-value-quantity, component-data-absent-reason, component-value-concept, component-value-quantity, data-absent-reason, date, derived-from, device, encounter, focus, has-member, identifier, method, organization, part-of, patient, performer, specimen, status, subject, value-concept, value-date, value-quantity, value-string]\". Valid search parameters for this search are: {2}"

AC:

AWS FHIR Server returns 400 and an appropriate error message for invalid search params instead of an empty list.

**Comment by rsmayda** [comment]
Thanks for bringing this one up. I confirm we see this behavior too. We will keep this ticket updated with progress

**Comment by carvantes** [comment]
Hi, this enhancement was made as part of #36 and is part of the [fhir-works-on-aws-deployment 2.4.0 release](https://github.com/awslabs/fhir-works-on-aws-deployment/releases/tag/v2.4.0)

A request like `{{API_URL}}/Observation?foo=bar` now fails with a 400 error:
```js
{
    "resourceType": "OperationOutcome",
    "text": {
        "status": "generated",
        "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><tr><td style=\"font-weight: bold;\">error</td><td>[]</td><td><pre>Invalid search parameter 'foo' for resource type Observation</pre></td></tr></table></div>"
    },
    "issue": [
        {
            "severity": "error",
            "code": "invalid",
            "diagnostics": "Invalid search parameter 'foo' for resource type Observation"
        }
    ]
}
```
