### ISSUE TITLE
[Feature Request]Support for "prefer" header

### ISSUE THREAD

**Issue by vvedantham** [awslabs/fhir-works-on-aws-search-es#180]
**Is your feature request related to a problem? Please describe.**
In several cases, client applications can send unsupported or unknown search parameters. Listed below are a couple of possible reasons for this to occur. 

1. Different implementations of FHIR: Different servers may support different search parameters - this could either be due to a difference in interpretation of the standard or a custom requirement. Client applications that are designed to be implementation agnostic may hence send search parameters that are not supported expecting the server to ignore any unknown parameters.
2. Additional parameters beyond client's control: Various HTTP stacks and proxies may add parameters that are not under the control of the client application.

While the FHIR implementation guide expects the server to ignore any unknown or unsupported parameters, using either a strict validation or no validation of parameters presents obstacles to onboarding new client applications.

![image](https://user-images.githubusercontent.com/28118500/155760483-28292d2e-1e8e-4801-ac0d-a95eace4216c.png)

This becomes a more pressing problem needing custom workarounds such as proxies to filter or modify parameters, if the fix for issue reported in #167 always performs strict validation,

**Describe the solution you'd like**
The recommended method to address this would be support for the "prefer" header (see Unknown and unsupported parameters) on [Search- Handling Errors](https://www.hl7.org/fhir/search.html#errors). The server could have a default configuration of prefer: handling = strict while a specific client can override with prefer: handling = lenient.

This would allow  control (either by the client application or a proxy) on the validation that is expected for the specific client.

**Describe alternatives you've considered**

1.  Have a proxy modify the search parameters to ensure only valid/supported search parameters are passed to the FHIR server.

**Additional context**

**Comment by Bingjiling** [comment]
Hi @vvedantham ,

Thanks for reaching out! I'll take this request back to the team.

Thanks,
Yanyu

**Comment by Bingjiling** [comment]
Hi @vvedantham,

Sadly we'll not be prioritizing this feature at the current point. If you're interested in implementing it yourself, here're the rough steps of how it could work: 

* Update interface package so the header can be passed into search package
* Update the routing package to parse and pass the header 
* Update search package to respect the prefer header - search for `InvalidSearchParameterError` in the package and decide which ones should be ignored 

Hope this helps!

Thanks,
Yanyu

**Comment by kcadette** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com](mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake](https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
