### ISSUE TITLE
[Feature Request] Allow Binary Search to place a "presignedGetUrl" or return object within "data" section

### ISSUE THREAD

**Issue by ghost** [awslabs/fhir-works-on-aws-search-es#185]
**Is your feature request related to a problem? Please describe.**
We have third party apis that retrieve data from our FHIR server and are expecting the "data" section of the JSON to contain the object.  Currently a pre-signed URL is returned with in the "presignedGetUrl".
Example:
{
    "meta": {
        "lastUpdated": "2022-03-01T17:57:13.228583Z",
        "versionId": "1"
    },
    "contentType": "application/xml",
    "resourceType": "Binary",
    "data": "",
    "id": "af227b54-f2d9-4eb5-821c-18614af7ab12",
    "presignedGetUrl": "Generated URL"
}
**Describe the solution you'd like**
We would like to be able to choose which section gets populated. For the object to actually be returned with in the data section.

**Describe alternatives you've considered**
Currently we are evaluating whether we can adjust these sections using a proxy after returning but before sending it to the third parties.

**Additional context**

**Comment by kcadette** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com](mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake](https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
