### ISSUE TITLE
[Misc] token search parameter use of multi_match

### ISSUE THREAD

**Issue by Zambonilli** [awslabs/fhir-works-on-aws-search-es#187]
**What's on your mind?**
We're performing load testing on some of our custom observation resource types and seeing very unstable behavior from elastic search when performing queries on Observation.code. Specifically, we're seeing our response times balloon into taking between 30-60 seconds and in some cases have caused the data nodes to go offline and 504 responses are returned from the elastic search load balancer for periods of time. Looking more into the issue, we were able to narrow down the unstable behavior to the use of multi_ match in the query when specifying an Observation.code value. Adding a system to the query helped marginally but it was until we went in and removed all of the token types besides CodeableConcept from the fields list did our load tests stabilize and we started getting a response time and p99 values all under 1 second.

There's a comment in the code section about needing the StructureDefinitions here to be able to prune the fields down or even use a match instead of multi_match. Has there been any new developments here? https://github.com/awslabs/fhir-works-on-aws-search-es/blob/mainline/src/QueryBuilder/typeQueries/tokenQuery.ts#L29

I'm seeing where the de-Observation.code StructureDefinition in the FHIR r4 specs and it is defining the field as a CodeableConcept. Am I correct in thinking the solution would be to add another field to the CompiledSearchParam types and regenerating the schema file to get the valid token data types into the tokenQuery context?

**Versions (please complete the following information):**
v2.5.1-smart `prod` stage

**Comment by Zambonilli** [comment]
We ended up writing a script to build a map of resource & path to token data type(s) from fhir r4 spec then load the map in tokenQuery.ts and lookup all token search parameter data types in the map. Admittedly, it's a pretty ugly solution but we needed to unblock our load testing so we can have confidence in bringing on a new workload.

Here's the relevant bits of what we did to get unblocked. Probably most useful long term is the logic in the tokenQuery.ts should be reusable once the IG compiler is updated to include the token data types. Happy to help on a long term solution that is better integrated with the IG compiler and search flow if needed. Otherwise, hopefully these snippets help you guys out.

_fhir-works-on-aws-search-es changes_
https://github.com/awslabs/fhir-works-on-aws-search-es/compare/mainline...ResMedOSS:fhir-works-on-aws-search-es:feature/search_token_data_types

_fhir-works-on-aws-deployment changes_
https://github.com/awslabs/fhir-works-on-aws-deployment/compare/mainline...ResMedOSS:fhir-works-on-aws-deployment:feature/search_token_data_types

**Comment by kcadette** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com](mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake](https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
