### ISSUE TITLE
[Feature Request] Allow the max chained param result size to be configurable

### ISSUE THREAD

**Issue by ghost** [awslabs/fhir-works-on-aws-search-es#188]
**Is your feature request related to a problem? Please describe.**
We are hitting situations where the max chained result size is exceeding 100 and providing more precise queries isn't reasonable for the user   

**Describe the solution you'd like**
Allow the max chained params result to be set through an environment variable

**Describe alternatives you've considered**
We are researching possibly breaking up the search into multiple requests.

**Additional context**
One example is searching for an encounter by a patient name where the Last Name has more that 100 results:
Encounter?patient:Patient.name=LastName&status=planned,arrived,triaged,in-progress,onleave,finished&_include:iterate=Encounter:patient

**Comment by Bingjiling** [comment]
Hi @medhost-bfindeisen,

Thanks for reaching out! I've added this request to our backlog. 

Thanks,
Yanyu

**Comment by ghost** [comment]
Thanks @Bingjiling,

To prevent breaking changes would you prefer this be passed optionally as part of the object literal after useKeywordSubFields with a default value of 100:

https://github.com/awslabs/fhir-works-on-aws-search-es/blob/mainline/src/elasticSearchService.ts#L101

Thanks,
Bill

**Comment by kcadette** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com](mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake](https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
