### ISSUE TITLE
[Misc] Construction of Wildcard Query on String with ":contains" modifier.

### ISSUE THREAD

**Issue by adamfara24** [awslabs/fhir-works-on-aws-search-es#189]
When generating the search for a String field that uses the ":contains" modifier, because a wildcard query is generated, should these fields should be appended with the ".keyword" suffix? Since a wildcard query is term-level. 

Looking at QueryBuilder/typeQueries/stringQuery.ts
It's appended for the ":exact" modifier
`    const keywordSuffix = modifier === 'exact' ? '.keyword' : '';
`
But not for the ":contains" modifier 
`const queries = fields.map((field) => ({
            wildcard: {
                [field]: {
                    value: `*${value.toLowerCase()}*`,
                },
            },
        }));`
 
After testing with what is generated for the "address:contains" and running it against some test data (with mappings auto generated), data was only returned when I added in the .keyword field, for example when using the "address:contains" output found in the test file. 

I suppose if your mappings had the all of the address fields were of type keyword you would not need it, if I understand this correctly. However I since I don't see the "uses_mappings" check in this portion of the codebase I'm unsure if this is intended.

https://www.elastic.co/guide/en/elasticsearch/reference/8.5/term-level-queries.html

Please let me know what you think.
Thanks!

**Comment by ssvegaraju** [comment]
Hi @adamfara24,
Thanks for bringing up this question! Just to make sure I understand correctly, you're asking if the `:contains` modifier will search all attributes of a resource? 

If so, I think we don't have to. As per the FHIR Spec: https://www.hl7.org/fhir/search.html#string, contains can match anywhere within the field that is being searched. I believe we check each field for a match with `*value*` (defined in the search mappings in this folder: https://github.com/awslabs/fhir-works-on-aws-search-es/tree/mainline/src/schema), whereas with `:exact`, we do have to indicate the keyword suffix to ensure its an strict/exact match. Let me know if I missed something, a few examples may help me understand better!

Thanks for your time,
Sukeerth

**Comment by adamfara24** [comment]
Hello Sukeerth,

I appreciate the quick reply!

I think we are in agreement with everything you stated there, my question is a little different, I'll try to clarify a little better here. 

So like you said, the :contains modifier searches across all fields for the type, I'll use address as an example here.

`{
      "wildcard": {
        "address.state": {
          "value": "*P*"
        }
      }
    }, {
      "wildcard": {
        "address.text": {
          "value": "*123 something rd*"
        }
      }
    }`

This is 2 of the 7(ish) that are generated when you search Patient.address with modiifer :contains, and all wrapped in a boolean.  (omitting the others for brevity.)

My thought is that, instead they should look like this:


`{
      "wildcard": {
        "address.state.keyword": {
          "value": "*P*"
        }
      }
    }, {
      "wildcard": {
        "address.text.keyword": {
          "value": "*123 something rd*"
        }
      }
    }`


Not because we are looking for an exact match (Like the case of :exact, which you mention above) 
But instead because wildcard searches must be done on term-level queries, rather than full-text. 

When testing out the queries that are generated when using no modifiers, I was able to get results back locally as expected.
When I attempted to use the queries generated with the :contains modifier, I noticed it was not returning results. That sent me down this path until I was able to get results back by appending the .keyword to the query generated with the :contains modifier. 

An example of someone asking a similar question would be 
https://stackoverflow.com/questions/44868097/elastic-search-why-does-wildcard-query-return-no-result

It seems counterintuitive that the wildcards would use the same fields as one would for 'exact' matches, but the details at https://www.elastic.co/guide/en/elasticsearch/reference/8.5/term-level-queries.html seem to back that, and it works for me locally as well. 

Do my findings make sense? Or do I perhaps have something odd going on in my local environment. 

Thanks again! 

Adam

**Comment by ssvegaraju** [comment]
This makes sense to me! I would like a bit more information on what queries were returning no results, but I think the decision we've come to as a team on our end is to not change these mappings to have the `.keyword` suffix. This is because this would require re-indexing almost every resource attribute in the cluster to be a keyword type, which is non-trivial and may affect existing deployments. However, given that the change needed is rather small, we'd encourage you to customize the code to achieve the behavior your looking for. 

Thanks again for the deep dive on this!
-Sukeerth
