### ISSUE TITLE
Console.log left enabled in processIterativeSearchInclusions()

### ISSUE THREAD

**Issue by AllanHodkinson** [awslabs/fhir-works-on-aws-search-es#19]
Hi AWS team,
We are seeing lots of Cloudwatch log entries from the search module when doing routine FHIR operations:
```
2020-10-12T11:04:46.974Z 767c85a9-9a61-4adf-8ce7-eb57dec7d1c2 INFO Iterative inclusion search starts
2020-10-12T11:04:46.975Z 767c85a9-9a61-4adf-8ce7-eb57dec7d1c2 INFO Iteration 0 found zero results. Stopping
```
Looks like these need disabling or setting debug-only?

Many thanks,
Allan

**Comment by nguyen102** [comment]
Hi Allan,

Thanks for bringing this to our attention. We'll discuss this issue with the team and will get back to you soon.
Tim

**Comment by nguyen102** [comment]
After discussion with the dev team, we've decided to implement a refactoring of the search code. When a search request is made that does not include the query params `_include:iterate` or `_revinclude:iterate`, we won't continue processing iterative inclusions. As a result, the log entries that was mentioned in this Github issue won't be outputted to CW Logs. 

The PR for that is here.
https://github.com/awslabs/fhir-works-on-aws-search-es/pull/20

We currently have a ticket in our Backlog to incorporate a Logging system to allow logging different severity levels. E.g. info, debug, error... Once that ticket is prioritized and completed, these log lines will be logged only for debugging purposes.

**Comment by AllanHodkinson** [comment]
Sounds like a good solution, thanks.
