### ISSUE TITLE
There is no mechanism to failover to search from DynamoDB or any other resource

### ISSUE THREAD

**Issue by akasmika-commits** [awslabs/fhir-works-on-aws-search-es#21]
Attaching the Q&A from a separate conversation:

1. What is the mechanism for Elastic Search (ES) failover ? Because search operation is tightly coupled with ES.

A: This has not yet been tested; we will put this on the backlog to perform. The expected behavior is that the Lambda function triggered by DynamoDB Streams when the write to DynamoDB occurs will fail during the ES failover; we would like to address this more gracefully.

2. What is the mechanism of Elastic Search sync (Dynamo Stream Sync) after failover.

A: This has not yet been tested; we will put this on the backlog to perform. The expected behavior is that the Lambda function triggered by DynamoDB Streams when the write to DynamoDB occurs will be able to write to the cluster as before.

**Comment by nguyen102** [comment]
By spreading your ES master nodes and data nodes into three availability zones it should minimize the chance of ES being down and therefore unreachable by your `ddbToEs` lambda. [Link here](https://aws.amazon.com/blogs/database/increase-availability-for-amazon-elasticsearch-service-by-deploying-in-three-availability-zones-2/)

However, it is important that we implement mechanisms to ensure that all records from DDB are written to ES in case of a network error or other issues in which `ddbToEs` fail to write to ES in the first try. 
Possible solutions include writing failed requests to a dead letter queue to be processed at a later time. Or to implement exponential back off time for writing the failed requests to ES. 

I'll add a ticket to our back log for this story (FHIR-385).

**Comment by rsmayda** [comment]
This issue is the same as the persistence layer issue: https://github.com/awslabs/fhir-works-on-aws-persistence-ddb/issues/18

Leaving both open as it affects persistence and search components

**Comment by rsmayda** [comment]
We are now logging failures into a DLQ and improved logging to identify the problematic resources
