### ISSUE TITLE
Search Resource by multiple identifiers does not work.

### ISSUE THREAD

**Issue by akasmika-commits** [awslabs/fhir-works-on-aws-search-es#22]
Updates from previous conversations

Search Resource by multiple identifiers does not work.

- Example: https://<host>/Patient/?identifier.system=AccountNumber&identifier.value=21334&identifier.system=mrn&identifier.value=1234
- HAPI FHIR sample that works with multiple identifier search: http://hapi.fhir.org/baseR4/Patient?identifier=http://hospital.smarthealthit.org|2906be73-5a0b-438b-91adffca6692692c&identifier=http://hl7.org/fhir/sid/us-ssn|999-45-7927&_pretty=true
- FHIR spec also mentions about using pipeline (|) character with code and system search. Fireworks doesn’t seem to be searching with pipeline
  - https://www.hl7.org/fhir/search.html
  - A parameter may refer to a non-existent resource e.g. GET [base]/Observation?patient.identifier=http://example.com/fhir/identifier/mrn|123456
- Range date search is not possible
  - https:///AllergyIntolerance?onsetDateTime=gt2001-10-20

FHIR Works on AWS MVP release on 28th August 2020 included only basic search functionality, with a view to gaining customer feedback to identify what enhancements should be prioritized. Near-term roadmap functionality for search will support _include and _revinclude parameters.

**Comment by nguyen102** [comment]
Thanks for your feedback Akas. 
5. Is currently in our backlog
A. `_include` and `_revinclude` has now been published in version 1.1
https://github.com/awslabs/fhir-works-on-aws-search-es/blob/mainline/CHANGELOG.md

**Comment by rsmayda** [comment]
In our most recent release we fixed a lot of date related search issues and included token enhancement: https://github.com/awslabs/fhir-works-on-aws-deployment/tree/v2.6.0

Could you ensure you are using the latest versions? If issues persist please reopen this issue 😄
