### ISSUE TITLE
AWS region us-west-2 hardcoded in IS_OFFLINE mode

### ISSUE THREAD

**Issue by emilhdiaz** [awslabs/fhir-works-on-aws-search-es#23]
We are attempting to run the `fhir-service` lambda locally with the environment variable `IS_OFFLINE=true`, but while still communicating with real DynamoDB and ElasticSearch instances in the us-east-1 AWS region.

When the `IS_OFFLINE` environment variable is set, the AWS Javascript SDK is reconfigured to use the (hard-coded) `us-west-2` region. This region should also be detected from environment variables so that it can be dynamically configured. This would allow a local instance of the `fhir-service` server to communicate with AWS resource in the region of choice.

Version: v2.0.1

**Comment by rsmayda** [comment]
Thanks for creating a PR for this! Will review PR when out of 'DRAFT'

**Comment by emilhdiaz** [comment]
Thanks @rsmayda ! This has now been compiled, deployed and manually tested in one of our internal development environments.

**Comment by rsmayda** [comment]
Merged into mainline will most likely be released (in NPM package) sometime next week
