### ISSUE TITLE
Support for custom search parameters

### ISSUE THREAD

**Issue by AllanHodkinson** [awslabs/fhir-works-on-aws-search-es#49]
Hi AWS team,
Can you give us a status update on custom search parameters in ES please?  I can see that some of this has been done in the feat-search-igs branch but that work looks to have stalled for the moment.
Many thanks,
Allan

**Comment by jn1119** [comment]
Hi Allan,

Thanks for reaching out. Yes, the development is still in progress and it is a high priority for us. 

Also, I should include that our current work would support all search parameters except [DocRef](https://www.hl7.org/fhir/us/core/OperationDefinition-docref.html) in the following IGs:
1. US Core (hl7.fhir.us.core)
2. CARIN Blue Button (hl7.fhir.us.carin-bb)
3. Payer Data Exchange (hl7.fhir.us.davinci-pdex)
4. DaVinci Payer Data Exchange US Drug Formulary (hl7.fhir.us.Davinci-drug-formulary)
5. DaVinci PDEX Plan Net (hl7.fhir.us.davinci-pdex-plan-net)

Let us know if you have any feedback, questions or concerns. Thanks

**Comment by AllanHodkinson** [comment]
Hi Jeet,
Thanks for the prompt response & information.  We are using mostly standard R4 search parameters but there are a couple of use cases in our service that need a custom search.
What do you think the timescale for the implementation will be?
Thanks.
Allan

**Comment by jn1119** [comment]
Hi Allan, do you have some timeline by which you would want the feature to be released? Also, does the feature work I included in my response earlier works for you? Just making sure that our release would address your requirements.

Thanks,
Jeet

**Comment by AllanHodkinson** [comment]
Hi Jeet,
This feature is blocking us from using >= v2.0.0 of the ES component, so ideally we'd like to see this rolled out in a month or less if possible.
I haven't looked into the IGs you listed but I wouldn't expect the search params we've added to be present - they are extensions to the DeviceDefinition resource search params.
Thanks,
Allan

**Comment by jn1119** [comment]
Hi Allan, Do the extensions in DeviceDefinition come from a standard IG or do you have your own custom IG?

Thanks,
Jeet

**Comment by AllanHodkinson** [comment]
No we've written our own IG for this.

**Comment by carvantes** [comment]
Hi,

We'll be releasing the IG support before the end of this month. The current work in progress is on the `feat-search-igs` branch.

It will be possible to use your own custom parameters. to do this, you'll need to create a custom IG package with the search parameters you've authored. Search parameters should conform to the `SearchParameter` spec and have both a `FHIRpath` and an `XPath` expression.

**Comment by AllanHodkinson** [comment]
That's great thanks
