### ISSUE TITLE
Support more robust searching

### ISSUE THREAD

**Issue by rsmayda** [awslabs/fhir-works-on-aws-search-es#7]
Currently our search is completed by using ['keyword'](https://www.elastic.co/guide/en/elasticsearch/reference/current/keyword.html). This leaves much to be desired and required from the FHIR spec. Such as:

- ~~Date range search~~ (https://github.com/awslabs/fhir-works-on-aws-search-es/pull/61)
- ~~Greater/less than quantity search~~ (https://github.com/awslabs/fhir-works-on-aws-search-es/pull/58)
- Support for parameters for all resources 
  - Sorting on any parameter is not supported yet
- Search result parameters (ie sorting results)
  - Sort available by `date type field` only (https://github.com/awslabs/fhir-works-on-aws-search-es/pull/60)

FHIR spec for context:
- https://www.hl7.org/fhir/http.html#search
- https://www.hl7.org/fhir/search.html

A/C:
- Add functionality
- Update integration test

**Comment by lwarren01** [comment]
We have observed the following issue, which we think falls into the category of more robust search support. When searching using reference parameters it is not performing an exact match of the referenced resource ID. For example, all of the following return the same set of resources:

- /Patient?organization=19d9bd55-56fc-4d19-850f-2c1ee651aefb
- /Patient?organization=19d9bd55
- /Patient?organization=19d9bd55-56fc-4d19-850f-2c1ee651aefb_INVALID_SUFFIX

**Comment by luisberga** [comment]
Hello! 

@lwarren01 this bug is exactly what I need to do in the project that I'm working for.

@rsmayda Do we have a solution forecast for this case? Would there be any way to help you? Due to the progress of the project I'm working on, I have a certain urgency to have this functionality

**Comment by rsmayda** [comment]
@lwarren01 & @luisberga  thanks for calling this out we will try to reproduce it this week and get back to you

**Comment by carvantes** [comment]
@lwarren01 & @luisberga , the exact reference match was brought up on a separate issue: https://github.com/awslabs/fhir-works-on-aws-deployment/issues/329. The fix for it has been released on fhir-works-on-aws-search-es@2.6.1

**Comment by Zambonilli** [comment]
We are seeing references with logical `identifier` not matching results as well.

E.G: POST AuditEvent w/agent.who logical identifier reference
```
"who": {
    "identifier": "f1d8e233-6c7b-4265-b18f-af286820158c",
    "type": "Patient"
}
```

**Comment by lindenquan** [comment]
It seems search parameters that have "-" are not supported. For example In the Group resource, there is a search parameter called "characteristic-value". And I cannot use this parameter

**Comment by ghost** [comment]
We would like to see the contains string search added:

**[base]/Patient?given:contains=eve**	

Any patients with a name with a given part containing "eve" at any position. This would include patients with the given name "Eve", "Evelyn", and also "Severine".

Of course it would be nice to support all 3 string search scenarios mentioned in 3.1.1.4.8:

- **[base]/Patient?given=eve**	
  Any patients with a name containing a given part with "eve" at the start of the name. This would include patients with the given name "Eve", "Evelyn".

- **[base]/Patient?given:contains=eve**	
  Any patients with a name with a given part containing "eve" at any position. This would include patients with the given name "Eve", "Evelyn", and also "Severine".

- **[base]/Patient?given:exact=Eve**	
  Any patients with a name with a given part that is exactly "Eve". Note: This would not include patients with the given name "eve" or "EVE".

**Comment by kcadette** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com](mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake](https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
