### ISSUE TITLE
[Feature Request] generate schema mapping from implementation guides

### ISSUE THREAD

**Issue by justinusmenzel** [awslabs/fhir-works-on-aws-search-es#82]
**Is your feature request related to a problem? Please describe.**
* Right now the elastic search schema mapping is created during dynamo db to elastic sync using one index per resource type. If the index for the current resource type isn't found, one is generated using a basic mapping that's not specific to the resource type. 
* Dynamic mapping takes care of creating all the other attribute type mappings whenever the first resource is being loaded into the index. This leads to an unpredictable mapping if the imported data isn't all looking exactly the same. 
It also leads to a bloat since a lot of attributes are being mapped that are never used in search. 

**Describe the solution you'd like**
* Use the IG compilation step to generate the schema mapping based on SearchParameters
* Disable dynamic mapping

**Comment by SanketD92** [comment]
Hello @justinusmenzel, thank you for opening this issue.

We'll add this to our backlog and pull it into upcoming sprints with respect to priority.

**Comment by kcadette** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com](mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake](https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
