### ISSUE TITLE
Specify operator for multi-filter match queries

### ISSUE THREAD

**Issue by arthuston** [awslabs/fhir-works-on-aws-search-es#83]
Bug Report:

Currently the code that translates a FWoA SearchFilter into an Elasticsearch query filter honor the operator for multivalue filters, but has no way to specify the operator for multi-filter match queries. 

For example, when calling getPatientByMid('foo'), the following SearchFilter(s) are passed to ElasticSearchService.buildElasticSearchFilter():

Which produces a query filter that looks like this (notice the absence of the joining operators): 

And results in an ES query that looks like this (notice the presence of the OR operators): 
```json
{
  "from": 0,
  "size": 20,
  "query": {
    "bool": {
      "filter": [
        {
          "match": {
            "documentStatus": {
              "query": "AVAILABLE",
              "operator": "OR",
              "prefix_length": 0,
              "max_expansions": 50,
              "fuzzy_transpositions": true,
              "lenient": false,
              "zero_terms_query": "NONE",
              "auto_generate_synonyms_phrase_query": true,
              "boost": 1
            }
          }
        },
        {
          "match": {
            "__internalMeta.contexts.identifiers.value": {
              "query": "foo",
              "operator": "OR",
              "prefix_length": 0,
              "max_expansions": 50,
              "fuzzy_transpositions": true,
              "lenient": false,
              "zero_terms_query": "NONE",
              "auto_generate_synonyms_phrase_query": true,
              "boost": 1
            }
          }
        }
      ],
      "adjust_pure_negative": true,
      "boost": 1
    }
  }
}
```
This occurs because when an operation is omitted in a search query, ES defaults to an OR operator. 

See:   

The __internalMeta.contexts.identifiers.value field is being analyzed by ES with an analyzer that is splitting up the value by common delimiters (i.e spaces, dashes, underscores). In the case of Cambia’s business identifiers (i.e. foo-bar-baz) this results in search for all documents that match  __internalMeta.contexts.identifiers.value = foo OR bar OR baz

Resolution: 

The ElasticSearchService.buildElasticSearchFilterPart() method needs to be modified so that it can honor the operator that was passed in via the SearchFilter objects. However we need to confirm with AWS if these operators were intended for multi-value match queries OR multi-match queries filter.

We need change the analyzer used for this field so that the field value is not split along common delimiters.

**Comment by rsmayda** [comment]
Hey! Thanks for opening the ticket. My suggestion would be to statically map your internalMeta  index ` __internalMeta.contexts.identifiers.value` to being a `keyword` as seen here: https://github.com/awslabs/fhir-works-on-aws-persistence-ddb/blob/mainline/src/ddbToEs/ddbToEsHelper.ts#L65
