### ISSUE TITLE
[Bug] Issue using _include with location

### ISSUE THREAD

**Issue by ghost** [awslabs/fhir-works-on-aws-search-es#94]
**Describe the bug**
When using _include with location it is not returning the location resource.

**To Reproduce**
You will need a patient with an encounter that contains a location.
Then Run:
/Encounter?_include:iterate=Encounter:patient&_include:iterate=Encounter:location&patient=Patient/2e3bc8ff-8a25-46ee-9cd7-c87b05cacb5d

**Expected behavior**
I would expect it to also return the location resource as part of the _include. 

**Additional context**
It does return encounter and patient resource using the _include.

**Comment by carvantes** [comment]
Hi,

thanks for bringing this up. The issue has been fixed as part of https://github.com/awslabs/fhir-works-on-aws-search-es/pull/97 and it will released soon

**Comment by SanketD92** [comment]
The fix has now been released with the latest release (v3.2.1).
