### ISSUE TITLE
Issue Searching Resource by multiple identifiers

### ISSUE THREAD

**Issue by ghost** [awslabs/fhir-works-on-aws-search-es#95]
**Describe the bug**
When searching by multiple identifiers it is not returning multiple resources

**To Reproduce**
Example:
/Observation?patient=Patient/1a6e4b54-b756-49a6-ae7e-5f7ec27d5896&category=vital-signs&code=8867-4,9279-1,85354-9

**Expected behavior**
Should return multiple resources based on the codes.

**Additional context**
http://hl7.org/fhir/R4/observation-vitalsigns.html

**Comment by carvantes** [comment]
Hi, 

The OR search parameters (comma) were not previously supported. We just released support for it as part of v3.2.0.(https://github.com/awslabs/fhir-works-on-aws-search-es/pull/93)

Please update to fhir-works-on-aws-search-es@3.2.0
